<a href="https://colab.research.google.com/github/kittikhun62/DWDM21/blob/main/Data_Preprecessing(%E0%B9%84%E0%B8%A7%E0%B9%89%E0%B8%9D%E0%B8%B6%E0%B8%81%E0%B8%97%E0%B8%B3%E0%B8%82%E0%B9%89%E0%B8%AD%E0%B8%AA%E0%B8%AD%E0%B8%9A).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

In [4]:
path = '/content/drive/My Drive/MID'

In [6]:
data = pd.read_csv(os.path.join(path,'mf_portfif_1_th_06.csv'))

In [7]:
data

                                     ภูมิภาคและประเทศ  ... มิถุนายน_ปี_2564
0                                             Africa   ...     1.350281e+01
1                                           mauritius  ...              NaN
2                                            morocco   ...              NaN
3                                       south africa   ...     1.350281e+01
4                                               togo   ...              NaN
..                                                ...  ...              ...
85                                     supranational   ...              NaN
86                                             TOTAL   ...     1.763376e+06
87                                                NaN  ...              NaN
88   *Europe Region หมายถึง มูลค่าการลงทุนผ่านหน่ว...  ...              NaN
89                      **ไม่รวมสัญญาซื้อขายล่วงหน้า   ...              NaN

[90 rows x 56 columns]

In [8]:
data['กรกฎาคม_ปี_2562']

0             86.1
1                0
2            14.19
3            65.42
4             6.49
          ...
85          275.86
86    1,688,435.04
87             NaN
88             NaN
89             NaN
Name: กรกฎาคม_ปี_2562, Length: 90, dtype: object

In [9]:
data.isnull()

    ภูมิภาคและประเทศ  ธันวาคม_ปี_2559  ...  พฤษภาคม_ปี_2564  มิถุนายน_ปี_2564
0              False            False  ...            False             False
1              False            False  ...             True              True
2              False            False  ...             True              True
3              False            False  ...            False             False
4              False            False  ...             True              True
..               ...              ...  ...              ...               ...
85             False            False  ...             True              True
86             False            False  ...            False             False
87              True             True  ...             True              True
88             False             True  ...             True              True
89             False             True  ...             True              True

[90 rows x 56 columns]

In [12]:
data.isnull().any()

ภูมิภาคและประเทศ      True
ธันวาคม_ปี_2559       True
มกราคม_ปี_2560        True
กุมภาพันธ์_ปี_2560    True
มีนาคม_ปี_2560        True
เมษายน_ปี_2560        True
พฤษภาคม_ปี_2560       True
มิถุนายน_ปี_2560      True
กรกฎาคม_ปี_2560       True
สิงหาคม_ปี_2560       True
กันยายน_ปี_2560       True
ตุลาคม_ปี_2560        True
พฤศจิกายน_ปี_2560     True
ธันวาคม_ปี_2560       True
มกราคม_ปี_2561        True
กุมภาพันธ์_ปี_2561    True
มีนาคม_ปี_2561        True
เมษายน_ปี_2561        True
พฤษภาคม_ปี_2561       True
มิถุนายน_ปี_2561      True
กรกฎาคม_ปี_2561       True
สิงหาคม_ปี_2561       True
กันยายน_ปี_2561       True
ตุลาคม_ปี_2561        True
พฤศจิกายน_ปี_2561     True
ธันวาคม_ปี_2561       True
มกราคม_ปี_2562        True
กุมภาพันธ์_ปี_2562    True
มีนาคม_ปี_2562        True
เมษายน_ปี_2562        True
พฤษภาคม_ปี_2562       True
มิถุนายน_ปี_2562      True
กรกฎาคม_ปี_2562       True
สิงหาคม_ปี_2562       True
กันยายน_ปี_2562       True
ตุลาคม_ปี_2562        True
พฤศจิกายน_ปี_2562     True
ธันวาคม_ปี_2562       True
มกราคม_ปี_2563        True
กุมภาพันธ์_ปี_2563    True
มีนาคม_ปี_2563        True
เมษายน_ปี_2563        True
พฤษภาคม_ปี_2563       True
มิถุนายน_ปี_2563      True
กรกฎาคม_ปี_2563       True
สิงหาคม_ปี_2563       True
กันยายน_ปี_2563       True
ตุลาคม_ปี_2563        True
พฤศจิกายน_ปี_2563     True
ธันวาคม_ปี_2563       True
มกราคม_ปี_2564        True
กุมภาพันธ์_ปี_2564    True
มีนาคม_ปี_2564        True
เมษายน_ปี_2564        True
พฤษภาคม_ปี_2564       True
มิถุนายน_ปี_2564      True
dtype: bool

In [14]:
data.head(50)

                        ภูมิภาคและประเทศ  ... มิถุนายน_ปี_2564
0                                Africa   ...        13.502806
1                              mauritius  ...              NaN
2                               morocco   ...              NaN
3                          south africa   ...        13.502806
4                                  togo   ...              NaN
5                          Asia Pacific   ...    103903.246300
6                             australia   ...      1988.800918
7                              cambodia   ...              NaN
8                             indonesia   ...      7266.207955
9      lao people’s democratic republic   ...       980.961121
10                             malaysia   ...      3815.351802
11                              myanmar   ...              NaN
12                          new zealand   ...         4.983263
13                          philippines   ...       589.789940
14                            singapore   ...     76045.807310
15                              vietnam   ...     13211.343950
16                         Eastern Asia   ...    560381.728500
17                                china   ...    414542.774300
18                            hong kong   ...    129298.794000
19                                japan   ...     12853.652180
20                   korea, republic of   ...      3253.188459
21                                macau   ...         6.959483
22                             mongolia   ...              NaN
23                               taiwan   ...       426.360126
24                               Europe   ...    556722.686800
25                              austria   ...              NaN
26                              belgium   ...        13.002638
27                             bulgaria   ...              NaN
28                               cyprus   ...              NaN
29                       czech republic   ...              NaN
30                              denmark   ...              NaN
31                       Europe Region*   ...     34301.538970
32                              finland   ...              NaN
33                               france   ...      1396.309558
34                              germany   ...      1264.670624
35                              hungary   ...              NaN
36                              iceland   ...              NaN
37                              ireland   ...    149751.431100
38                                italy   ...        66.904461
39                               latvia   ...              NaN
40                        liechtenstein   ...      1148.834969
41                            lithuania   ...              NaN
42                           luxembourg   ...    346145.335800
43                                malta   ...        15.029092
44                          netherlands   ...        87.802652
45                               norway   ...        15.324689
46                               poland   ...        37.401963
47                             portugal   ...              NaN
48                              romania   ...              NaN
49                             slovakia   ...              NaN

[50 rows x 56 columns]

In [15]:
data.tail(50)

                                     ภูมิภาคและประเทศ  ... มิถุนายน_ปี_2564
40                                     liechtenstein   ...     1.148835e+03
41                                         lithuania   ...              NaN
42                                        luxembourg   ...     3.461453e+05
43                                             malta   ...     1.502909e+01
44                                       netherlands   ...     8.780265e+01
45                                            norway   ...     1.532469e+01
46                                            poland   ...     3.740196e+01
47                                          portugal   ...              NaN
48                                           romania   ...              NaN
49                                          slovakia   ...              NaN
50                                          slovenia   ...              NaN
51                                             spain   ...              NaN
52                                            sweden   ...              NaN
53                                       switzerland   ...     7.142400e+02
54                                            turkey   ...              NaN
55                                    united kingdom   ...     2.176486e+04
56                          virgin islands (british)   ...              NaN
57                                       Middle East   ...     3.294298e+05
58                                           bahrain   ...              NaN
59                                            israel   ...              NaN
60                                        kazakhstan   ...              NaN
61                                            kuwait   ...     9.706834e+01
62                                              oman   ...     1.643898e+01
63                                             qatar   ...     3.031537e+05
64                                russian federation   ...     8.834706e+01
65                                      saudi arabia   ...     4.659756e+01
66                              united arab emirates   ...     2.602769e+04
67                                     North America   ...     2.059256e+05
68                                           bermuda   ...              NaN
69                                            canada   ...     2.421587e+02
70                                    cayman islands   ...     6.215345e+02
71                                            mexico   ...              NaN
72                                     united states   ...     2.050180e+05
73                             virgin islands (u.s.)   ...     4.394699e+01
74                                     South America   ...     4.861834e+01
75                                            brazil   ...     4.861834e+01
76                                             chile   ...              NaN
77                                          colombia   ...              NaN
78                                            panama   ...              NaN
79                                              peru   ...              NaN
80                                           uruguay   ...              NaN
81                                     Southern Asia   ...     6.668302e+03
82                                             india   ...     6.668302e+03
83                                         sri lanka   ...              NaN
84                                     supranational   ...              NaN
85                                     supranational   ...              NaN
86                                             TOTAL   ...     1.763376e+06
87                                                NaN  ...              NaN
88   *Europe Region หมายถึง มูลค่าการลงทุนผ่านหน่ว...  ...              NaN
89                      **ไม่รวมสัญญาซื้อขายล่วงหน้า   ...              NaN

[50 rows x 56 columns]

##ตัด colums สุดท้ายเพราะข้อมูลไม่ตรงกัน เเละมีช่องว่าง เเล้วค่อยทำ  missing